export const HAND_LANDMARK = {
  WRIST: 0,
  THUMB_CMC: 1,
  THUMB_MCP: 2,
  THUMB_IP: 3,
  THUMB_TIP: 4,
  INDEX_FINGER_MCP: 5,
  INDEX_FINGER_PIP: 6,
  INDEX_FINGER_DIP: 7,
  INDEX_FINGER_TIP: 8,
  MIDDLE_FINGER_MCP: 9,
  MIDDLE_FINGER_PIP: 10,
  MIDDLE_FINGER_DIP: 11,
  MIDDLE_FINGER_TIP: 12,
  RING_FINGER_MCP: 13,
  RING_FINGER_PIP: 14,
  RING_FINGER_DIP: 15,
  RING_FINGER_TIP: 16,
  PINKY_MCP: 17,
  PINKY_PIP: 18,
  PINKY_DIP: 19,
  PINKY_TIP: 20,
} as const;

export const PALM_LANDMARKS = [
  HAND_LANDMARK.WRIST,
  HAND_LANDMARK.INDEX_FINGER_MCP,
  HAND_LANDMARK.MIDDLE_FINGER_MCP,
  HAND_LANDMARK.RING_FINGER_MCP,
  HAND_LANDMARK.PINKY_MCP,
] as const;

export const FINGER_TIPS = [
  HAND_LANDMARK.THUMB_TIP,
  HAND_LANDMARK.INDEX_FINGER_TIP,
  HAND_LANDMARK.MIDDLE_FINGER_TIP,
  HAND_LANDMARK.RING_FINGER_TIP,
  HAND_LANDMARK.PINKY_TIP,
] as const;

export const HAND_CONNECTIONS: [number, number][] = [
  // Thumb
  [HAND_LANDMARK.WRIST, HAND_LANDMARK.THUMB_CMC],
  [HAND_LANDMARK.THUMB_CMC, HAND_LANDMARK.THUMB_MCP],
  [HAND_LANDMARK.THUMB_MCP, HAND_LANDMARK.THUMB_IP],
  [HAND_LANDMARK.THUMB_IP, HAND_LANDMARK.THUMB_TIP],
  // Index
  [HAND_LANDMARK.WRIST, HAND_LANDMARK.INDEX_FINGER_MCP],
  [HAND_LANDMARK.INDEX_FINGER_MCP, HAND_LANDMARK.INDEX_FINGER_PIP],
  [HAND_LANDMARK.INDEX_FINGER_PIP, HAND_LANDMARK.INDEX_FINGER_DIP],
  [HAND_LANDMARK.INDEX_FINGER_DIP, HAND_LANDMARK.INDEX_FINGER_TIP],
  // Middle
  [HAND_LANDMARK.INDEX_FINGER_MCP, HAND_LANDMARK.MIDDLE_FINGER_MCP],
  [HAND_LANDMARK.MIDDLE_FINGER_MCP, HAND_LANDMARK.MIDDLE_FINGER_PIP],
  [HAND_LANDMARK.MIDDLE_FINGER_PIP, HAND_LANDMARK.MIDDLE_FINGER_DIP],
  [HAND_LANDMARK.MIDDLE_FINGER_DIP, HAND_LANDMARK.MIDDLE_FINGER_TIP],
  // Ring
  [HAND_LANDMARK.MIDDLE_FINGER_MCP, HAND_LANDMARK.RING_FINGER_MCP],
  [HAND_LANDMARK.RING_FINGER_MCP, HAND_LANDMARK.RING_FINGER_PIP],
  [HAND_LANDMARK.RING_FINGER_PIP, HAND_LANDMARK.RING_FINGER_DIP],
  [HAND_LANDMARK.RING_FINGER_DIP, HAND_LANDMARK.RING_FINGER_TIP],
  // Pinky
  [HAND_LANDMARK.RING_FINGER_MCP, HAND_LANDMARK.PINKY_MCP],
  [HAND_LANDMARK.WRIST, HAND_LANDMARK.PINKY_MCP],
  [HAND_LANDMARK.PINKY_MCP, HAND_LANDMARK.PINKY_PIP],
  [HAND_LANDMARK.PINKY_PIP, HAND_LANDMARK.PINKY_DIP],
  [HAND_LANDMARK.PINKY_DIP, HAND_LANDMARK.PINKY_TIP],
];
